services:
  - type: web
    name: universal-partner
    runtime: node
    plan: free
    buildCommand: echo ok
    startCommand: node server.js
    envVars:
      - key: ADMIN_PASS
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
